In [3]:
import numpy as np

In [4]:
%timeit [x**4 for x in range(10)]

629 ns ± 36.9 ns per loop (mean ± std. dev. of 7 runs, 1,000,000 loops each)


In [5]:
%timeit  np.arange(1, 9)**4

1.75 µs ± 109 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)


In [6]:
lst = [14, 32, 93, 63, 69, 74]
numarray = np.array(lst)
numarray

array([14, 32, 93, 63, 69, 74])

In [7]:
numarray[::-2]

array([74, 63, 32])

In [11]:
numarray+10   #Same for other operator

array([ 24,  42, 103,  73,  79,  84])

In [14]:
np.sum(numarray)
np.mean(numarray)
np.max(numarray)

93