In [2]:
import numpy as np

In [3]:
%timeit [x**4 for x in range(10)]

521 ns ± 4.14 ns per loop (mean ± std. dev. of 7 runs, 1,000,000 loops each)


In [4]:
%timeit  np.arange(1, 9)**4

1.66 µs ± 21.9 ns per loop (mean ± std. dev. of 7 runs, 1,000,000 loops each)


In [13]:
lst = [14, 32, 93, 63, 69, 74]
lst2 = [114, 31, 903, 3, 69, 744]
numarray1 = np.array(lst)
numarray2 = np.array(lst2)

In [6]:
numarray1[::-2]

array([74, 63, 32])

In [7]:
numarray1+10   #Same for other operator

array([ 24,  42, 103,  73,  79,  84])

In [8]:
np.sum(numarray1)
np.mean(numarray1)
np.max(numarray1)

93

In [9]:
numarray1 * (np.pi / 180)

array([0.2443461 , 0.55850536, 1.6231562 , 1.09955743, 1.20427718,
       1.29154365])

In [12]:
#Trigo function take value in radian.
np.sin(np.pi/2)
np.sin(numarray1)

array([ 0.99060736,  0.55142668, -0.94828214,  0.1673557 , -0.11478481,
       -0.98514626])

In [14]:
numarray1 + numarray2

array([128,  63, 996,  66, 138, 818])