In [2]:
import numpy as np

In [3]:
%timeit [x**4 for x in range(10)]

585 ns ± 53.3 ns per loop (mean ± std. dev. of 7 runs, 1,000,000 loops each)


In [4]:
%timeit  np.arange(1, 9)**4

2.08 µs ± 435 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)


In [5]:
lst = [14, 32, 93, 63, 69, 74]
lst2 = [114, 31, 903, 3, 69, 744]
lst3 = [10, 310, 90, 30, 60, 40]
numarray1 = np.array(lst)
numarray2 = np.array(lst2)
numarray3 = np.array(lst3)

In [6]:
numarray1[::-2]

array([74, 63, 32])

In [7]:
numarray1+10   #Same for other operator

array([ 24,  42, 103,  73,  79,  84])

In [8]:
np.sum(numarray1)
np.mean(numarray1)
np.max(numarray1)

93

In [9]:
numarray1 * (np.pi / 180)

array([0.2443461 , 0.55850536, 1.6231562 , 1.09955743, 1.20427718,
       1.29154365])

In [10]:
#Trigo function take value in radian.
np.sin(np.pi/2)
np.sin(numarray1)

array([ 0.99060736,  0.55142668, -0.94828214,  0.1673557 , -0.11478481,
       -0.98514626])

In [11]:
numarray1 + numarray2

array([128,  63, 996,  66, 138, 818])

In [12]:
np.multiply(numarray1, numarray2)

array([ 1596,   992, 83979,   189,  4761, 55056])

In [13]:
np.concatenate((numarray1, numarray2))

array([ 14,  32,  93,  63,  69,  74, 114,  31, 903,   3,  69, 744])

In [54]:
x = np.array((numarray1, numarray2, numarray3))
#Both have same output
y = np.array([numarray1, numarray2])
y

array([[ 14,  32,  93,  63,  69,  74],
       [114,  31, 903,   3,  69, 744]])

In [15]:
print(x.ndim)
print(x.shape)   # return matrix dimension 3X6
print(y.shape)   # return matrix dimension 2X6

2
(3, 6)
(2, 6)


In [16]:
print(x)
print(x[0:3, 3:5])   #includes rows 0, 1, and 2, and columns 3 and 4.
print(x[0:3, 4:5])

[[ 14  32  93  63  69  74]
 [114  31 903   3  69 744]
 [ 10 310  90  30  60  40]]
[[63 69]
 [ 3 69]
 [30 60]]
[[69]
 [69]
 [60]]


In [33]:
numarray4 = np.array([[4, 1]])
np.concatenate((y, numarray4.T), axis=1)

array([[ 14,  32,  93,  63,  69,  74,   4],
       [114,  31, 903,   3,  69, 744,   1]])

In [43]:
# numarray1.reshape(2,3)
numarray1.reshape(2, 3)

array([[14, 32, 93],
       [63, 69, 74]])

In [47]:
y.reshape(4, -1)

array([[ 14,  32,  93],
       [ 63,  69,  74],
       [114,  31, 903],
       [  3,  69, 744]])

In [48]:
np.max(y)

903

In [50]:
np.max(y, axis=1)  #operations along the columns or the horizontal axis of a 2D array. 
np.max(y, axis=0)  #operations along the rows or the vertical axis of a 2D array. 

array([114,  32, 903,  63,  69, 744])

In [51]:
np.mean(y, axis=0)

array([ 64. ,  31.5, 498. ,  33. ,  69. , 409. ])

In [52]:
np.where(numarray1==14)  #return all index where condition satisfied.

(array([0], dtype=int64),)

In [53]:
np.where(y==14)  #you will get row index and column index.

(array([0], dtype=int64), array([0], dtype=int64))

In [59]:
np.sort(numarray1)
np.sort(y, axis=1)
np.sort(y, axis=0)

array([[ 14,  31,  93,   3,  69,  74],
       [114,  32, 903,  63,  69, 744]])

In [60]:
numarray1[numarray1 > 50]

array([93, 63, 69, 74])

In [63]:
y[y>50]

array([ 93,  63,  69,  74, 114, 903,  69, 744])

In [64]:
np.linspace(1,5,20)

array([1.        , 1.21052632, 1.42105263, 1.63157895, 1.84210526,
       2.05263158, 2.26315789, 2.47368421, 2.68421053, 2.89473684,
       3.10526316, 3.31578947, 3.52631579, 3.73684211, 3.94736842,
       4.15789474, 4.36842105, 4.57894737, 4.78947368, 5.        ])

In [65]:
np.arange(4, 20, 3)

array([ 4,  7, 10, 13, 16, 19])

In [68]:
np.zeros(10)
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [67]:
np.zeros((2, 3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [72]:
print(y + numarray1)  #this is known as broadcasting.
print(y + numarray1.T)  #this is known as broadcasting.
print(y)
print(numarray1)

[[ 28  64 186 126 138 148]
 [128  63 996  66 138 818]]
[[ 28  64 186 126 138 148]
 [128  63 996  66 138 818]]
[[ 14  32  93  63  69  74]
 [114  31 903   3  69 744]]
[14 32 93 63 69 74]


In [86]:
x = np.array([[1,2]])
print(y)
print(x.shape)
print(x.T.shape)
y + x.T

[[ 14  32  93  63  69  74]
 [114  31 903   3  69 744]]
(1, 2)
(2, 1)


array([[ 15,  33,  94,  64,  70,  75],
       [116,  33, 905,   5,  71, 746]])

In [96]:
#General multiplication.
f = numarray1 * numarray2

#Dot product of two array/vector
e = np.dot(numarray1, numarray2)
k = np.matmul(numarray1, numarray2)
l = numarray1@numarray2

In [107]:
np.matmul(y, numarray1)


array([ 24075, 146573])

In [108]:
np.ndarray.flatten(y)

array([ 14,  32,  93,  63,  69,  74, 114,  31, 903,   3,  69, 744])

In [111]:
y.reshape(1, -1)

# y.reshape(-1, 1)

array([[ 14,  32,  93,  63,  69,  74, 114,  31, 903,   3,  69, 744]])

In [112]:
np.random.rand(10)

array([0.06700855, 0.58480751, 0.78398841, 0.80781908, 0.45364422,
       0.71178338, 0.68051635, 0.84152807, 0.55505446, 0.90333645])

In [115]:
np.random.rand(3, 4)

array([[0.23325292, 0.53708489, 0.06357861, 0.94827379],
       [0.74018317, 0.36836304, 0.43922597, 0.65563668],
       [0.0975598 , 0.2046175 , 0.76449561, 0.85075636]])

In [119]:
np.random.randint(3, 10, 4)

array([9, 7, 4, 6])

In [120]:
np.random.randint(3, 10, (2, 4))

array([[5, 5, 8, 3],
       [6, 7, 7, 4]])