In [34]:
import numpy as np

In [35]:
%timeit [x**4 for x in range(10)]

416 ns ± 24.2 ns per loop (mean ± std. dev. of 7 runs, 1,000,000 loops each)


In [36]:
%timeit  np.arange(1, 9)**4

1.17 µs ± 5.83 ns per loop (mean ± std. dev. of 7 runs, 1,000,000 loops each)


In [55]:
lst = [14, 32, 93, 63, 69, 74]
lst2 = [114, 31, 903, 3, 69, 744]
lst3 = [10, 310, 90, 30, 60, 40]
numarray1 = np.array(lst)
numarray2 = np.array(lst2)
numarray3 = np.array(lst3)

In [38]:
numarray1[::-2]

array([74, 63, 32])

In [39]:
numarray1+10   #Same for other operator

array([ 24,  42, 103,  73,  79,  84])

In [40]:
np.sum(numarray1)
np.mean(numarray1)
np.max(numarray1)

93

In [41]:
numarray1 * (np.pi / 180)

array([0.2443461 , 0.55850536, 1.6231562 , 1.09955743, 1.20427718,
       1.29154365])

In [42]:
#Trigo function take value in radian.
np.sin(np.pi/2)
np.sin(numarray1)

array([ 0.99060736,  0.55142668, -0.94828214,  0.1673557 , -0.11478481,
       -0.98514626])

In [43]:
numarray1 + numarray2

array([128,  63, 996,  66, 138, 818])

In [44]:
np.multiply(numarray1, numarray2)

array([ 1596,   992, 83979,   189,  4761, 55056])

In [45]:
np.concatenate((numarray1, numarray2))

array([ 14,  32,  93,  63,  69,  74, 114,  31, 903,   3,  69, 744])

In [56]:
x = np.array((numarray1, numarray2, numarray3))
#Both have same output
y = np.array([numarray1, numarray2])

In [57]:
print(x.ndim)
print(x.shape)
print(y.shape)

2
(3, 6)
(2, 6)


In [66]:
print(x)
print(x[0:3, 3:5])
print(x[0:3, 4:5])

[[ 14  32  93  63  69  74]
 [114  31 903   3  69 744]
 [ 10 310  90  30  60  40]]
[[63 69]
 [ 3 69]
 [30 60]]
[[69]
 [69]
 [60]]
